// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Steal","status":true,"description":"Steal System with LUK-Based Success and Dynamic Loot","parameters":{}},
{"name":"ItemQuality","status":true,"description":"Item Quality System - Color Item Names Based on Quality","parameters":{}}
];
